/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Jason
 */
public class MenuAdm extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdm
     */
    public MenuAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divMenuAdm = new javax.swing.JPanel();
        divBotoes = new javax.swing.JPanel();
        botaoAddUsuário = new javax.swing.JButton();
        botaoAddProduto = new javax.swing.JButton();
        botaoAddEstoque = new javax.swing.JButton();
        botaoGerenciarVenda = new javax.swing.JButton();
        botaoGerarRela = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        foother = new javax.swing.JPanel();
        MyStock = new javax.swing.JLabel();
        Todos = new javax.swing.JLabel();
        c = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1012, 800));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(800, 700));

        divMenuAdm.setBackground(new java.awt.Color(255, 255, 255));
        divMenuAdm.setMaximumSize(new java.awt.Dimension(0, 0));
        divMenuAdm.setMinimumSize(new java.awt.Dimension(0, 0));
        divMenuAdm.setPreferredSize(new java.awt.Dimension(800, 700));

        divBotoes.setBackground(new java.awt.Color(255, 255, 255));
        divBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        botaoAddUsuário.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botaoAddUsuário.setText("Adicionar um novo usuário");
        botaoAddUsuário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddUsuárioActionPerformed(evt);
            }
        });

        botaoAddProduto.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botaoAddProduto.setText("Adicionar um novo produto");
        botaoAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddProdutoActionPerformed(evt);
            }
        });

        botaoAddEstoque.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botaoAddEstoque.setText("Gerenciar vendas");
        botaoAddEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddEstoqueActionPerformed(evt);
            }
        });

        botaoGerenciarVenda.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botaoGerenciarVenda.setText("Adicionar um novo estoque");
        botaoGerenciarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerenciarVendaActionPerformed(evt);
            }
        });

        botaoGerarRela.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        botaoGerarRela.setText("Gerar relatório ");
        botaoGerarRela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarRelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout divBotoesLayout = new javax.swing.GroupLayout(divBotoes);
        divBotoes.setLayout(divBotoesLayout);
        divBotoesLayout.setHorizontalGroup(
            divBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divBotoesLayout.createSequentialGroup()
                .addGap(0, 72, Short.MAX_VALUE)
                .addGroup(divBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoGerenciarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAddProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAddUsuário, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAddEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoGerarRela, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        divBotoesLayout.setVerticalGroup(
            divBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divBotoesLayout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(botaoAddUsuário)
                .addGap(18, 18, 18)
                .addComponent(botaoAddProduto)
                .addGap(18, 18, 18)
                .addComponent(botaoGerenciarVenda)
                .addGap(18, 18, 18)
                .addComponent(botaoAddEstoque)
                .addGap(18, 18, 18)
                .addComponent(botaoGerarRela)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(40, 203, 58));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_dark-removebg-preview 2.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        foother.setBackground(new java.awt.Color(40, 203, 58));
        foother.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        MyStock.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        MyStock.setText("MyStock ");

        Todos.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        Todos.setText("2024 Todos os direitos reservados");

        c.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        c.setText("©");

        javax.swing.GroupLayout footherLayout = new javax.swing.GroupLayout(foother);
        foother.setLayout(footherLayout);
        footherLayout.setHorizontalGroup(
            footherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footherLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(MyStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Todos)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        footherLayout.setVerticalGroup(
            footherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footherLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(footherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Todos)
                    .addComponent(c)
                    .addComponent(MyStock))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout divMenuAdmLayout = new javax.swing.GroupLayout(divMenuAdm);
        divMenuAdm.setLayout(divMenuAdmLayout);
        divMenuAdmLayout.setHorizontalGroup(
            divMenuAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(foother, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divMenuAdmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(divBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        divMenuAdmLayout.setVerticalGroup(
            divMenuAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divMenuAdmLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(divBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(foother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divMenuAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divMenuAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoGerarRelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarRelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoGerarRelaActionPerformed

    private void botaoGerenciarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerenciarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoGerenciarVendaActionPerformed

    private void botaoAddEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAddEstoqueActionPerformed

    private void botaoAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAddProdutoActionPerformed

    private void botaoAddUsuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddUsuárioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAddUsuárioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MyStock;
    private javax.swing.JLabel Todos;
    private javax.swing.JButton botaoAddEstoque;
    private javax.swing.JButton botaoAddProduto;
    private javax.swing.JButton botaoAddUsuário;
    private javax.swing.JButton botaoGerarRela;
    private javax.swing.JButton botaoGerenciarVenda;
    private javax.swing.JLabel c;
    private javax.swing.JPanel divBotoes;
    private javax.swing.JPanel divMenuAdm;
    private javax.swing.JPanel foother;
    private javax.swing.JPanel h1;
    private javax.swing.JPanel h2;
    private javax.swing.JPanel header;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
